runtime: python38  
instance_class: F2  
entrypoint: gunicorn -b :$PORT app:app 

automatic_scaling:  
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  min_idle_instances: 1
  max_idle_instances: 10

handlers:
- url: /static
  static_dir: static